name: Build and Notify

on: 
  push:  # This will trigger the workflow on any branch

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "I'm running on GitHub self-hosted Windows host "

      - name: Get Timestamp
        shell: powershell
        run: |
          $timestamp = (Get-Date).ToString('yyyyMMddHHmmss')
          Add-Content -Path $env:GITHUB_ENV -Value "timestamp=$timestamp"

      - name: Delete coreKushal folder if exists
        run: |
          if (Test-Path 'C:\Users\ParthibanEthiraj\OneDrive - Sinhal Udyog pvt ltd\Downloads\WorkFlow\coreKushal') {
            Remove-Item 'C:\Users\ParthibanEthiraj\OneDrive - Sinhal Udyog pvt ltd\Downloads\WorkFlow\coreKushal' -Recurse -Force
          }
        shell: powershell

      - name: Clone coreKushal Repository
        run: |
          cd 'C:\Users\ParthibanEthiraj\OneDrive - Sinhal Udyog pvt ltd\Downloads\WorkFlow'
          git clone https://github.com/parthibankimbal/coreKushal.git

      - name: Add commonCode Subtree
        run: |
          cd 'C:\Users\ParthibanEthiraj\OneDrive - Sinhal Udyog pvt ltd\Downloads\WorkFlow\coreKushal'
          git subtree add
