name: Build and Notify

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Print Message
        run: echo "I'm running on GitHub self-hosted Windows host"

      - name: Get Timestamp
        shell: powershell
        run: |
          $timestamp = (Get-Date).ToString('yyyyMMddHHmmss')
          Add-Content -Path $env:GITHUB_ENV -Value "timestamp=$timestamp"

      - name: Create WB_<timestamp> folder and copy utilityinfo
        run: |
          mkdir WB_${{ env.timestamp }}
          copy utilityinfo WB_${{ env.timestamp }}\

      - name: Upload WB_<timestamp> as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: WB_${{ env.timestamp }}
          path: WB_${{ env.timestamp }}